### ISSUE TITLE
Error in sibgif.js - Stream is not a constructor line 635

### ISSUE THREAD

**Issue by FlemmingH** [sibnerian/sibgif#2]
Hi

I need to use sibgif.js as transparent gif's placed over <img>. To get the canvas coordinates rendered i need to add something to the code, but there's an error in the sibgif.js. Could you add the latest dist of the non-minified version?

**Comment by sibnerian** [comment]
As far as I can tell, the _minified_ code still works in chrome/firefox.

If you just load the non-minified version, I would not expect it to work. `sibgif.js` depends `Stream.js`, `parseGif.js`, and `lzwDecode.js`. My guess is that's why you're getting "Stream is not a constructor".

If you want to make changes, you can still do that - you just need to build it after you edit the code. You can do that with just `gulp`.

Unfortunately I don't maintain this code anymore. Feel free to fork it if you need to make any changes!
